version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      official-actions:
        patterns: ['actions/*']
    commit-message:
      prefix: 'ci'
