-- Verified game set names from LibSets native API 101050 data (2026-05-25).
-- Source: https://github.com/Baertram/LibSets/blob/LibSets-reworked/LibSets/Data/LibSets_Data_SetNames.lua
-- Source blob: 27f0b016bfa0e669d7457b15e7fd2b0c7674590b
-- This finite name table covers the source snapshot, not arbitrary item names
-- or descriptions. Unknown identities retain their native names.
local Localization = AlphaSquadUI and AlphaSquadUI.Localization
if not Localization then return end
local sets = {
    [19] = { en = "Vestments of the Warlock", fr = "Les Vêtements du sorcier" },
    [20] = { en = "Witchman Armor", fr = "Armure d'homme-médecine" },
    [21] = { en = "Akaviri Dragonguard", fr = "La Garde du dragon akaviroise" },
    [22] = { en = "Dreamer's Mantle", fr = "Manteau du rêveur" },
    [23] = { en = "Archer's Mind", fr = "L’Esprit de l'archer" },
    [24] = { en = "Footman's Fortune", fr = "La Chance du valet" },
    [25] = { en = "Desert Rose", fr = "La Rose du désert" },
    [26] = { en = "Prisoner's Rags", fr = "Les Haillons de prisonnier" },
    [27] = { en = "Fiord's Legacy", fr = "L’Héritage de Fiord" },
    [28] = { en = "Barkskin", fr = "La Peau d'écorce" },
    [29] = { en = "Sergeant's Mail", fr = "La Cotte de mailles du sergent" },
    [30] = { en = "Thunderbug's Carapace", fr = "Carapace de foudroptère" },
    [31] = { en = "Silks of the Sun", fr = "Les Atours du soleil" },
    [32] = { en = "Healer's Habit", fr = "Le Froc du guérisseur" },
    [33] = { en = "Viper's Sting", fr = "La Morsure de la vipère" },
    [34] = { en = "Night Mother's Embrace", fr = "Étreinte de la Mère de la nuit" },
    [35] = { en = "Knightmare", fr = "Le Chevalier-cauchemar" },
    [36] = { en = "Armor of the Veiled Heritance", fr = "Armure de l'Héritage voilé" },
    [37] = { en = "Death's Wind", fr = "Le Vent mortel" },
    [38] = { en = "Twilight's Embrace", fr = "L’Étreinte du crépuscule" },
    [39] = { en = "Alessian Order", fr = "L’Ordre d'Alessia" },
    [40] = { en = "Night's Silence", fr = "Le Silence de la nuit" },
    [41] = { en = "Whitestrake's Retribution", fr = "La Rétribution de Blancserpent" },
    [43] = { en = "Armor of the Seducer", fr = "L’Armure de la séductrice" },
    [44] = { en = "Vampire's Kiss", fr = "Le Baiser du vampire" },
    [46] = { en = "Noble Duelist's Silks", fr = "Atours du noble duelliste" },
    [47] = { en = "Robes of the Withered Hand", fr = "Robes de la Main de Gloire" },
    [48] = { en = "Magnus' Gift", fr = "Le Présent de Magnus" },
    [49] = { en = "Shadow of the Red Mountain", fr = "L’Ombre du Mont Écarlate" },
    [50] = { en = "The Morag Tong", fr = "La Morag Tong" },
    [51] = { en = "Night Mother's Gaze", fr = "Le Regard de la Mère de la nuit" },
    [52] = { en = "Beckoning Steel", fr = "L’Appel de l'acier" },
    [53] = { en = "The Ice Furnace", fr = "Le Fourneau de glace" },
    [54] = { en = "Ashen Grip", fr = "La Poigne de cendres" },
    [55] = { en = "Prayer Shawl", fr = "Châle de prière" },
    [56] = { en = "Stendarr's Embrace", fr = "L’Étreinte de Stendarr" },
    [57] = { en = "Syrabane's Grip", fr = "L’Emprise de Syrabane" },
    [58] = { en = "Hide of the Werewolf", fr = "La Peau de loup-garou" },
    [59] = { en = "Kyne's Kiss", fr = "Le Baiser de Kyne" },
    [60] = { en = "Darkstride", fr = "Le Sentier obscur" },
    [61] = { en = "Dreugh King Slayer", fr = "Le Tueur du roi dreugh" },
    [62] = { en = "Hatchling's Shell", fr = "Coquille du rejeton" },
    [63] = { en = "The Juggernaut", fr = "Le Mastodonte" },
    [64] = { en = "Shadow Dancer's Raiment", fr = "La Parure du bateleur d'ombre" },
    [65] = { en = "Bloodthorn's Touch", fr = "Toucher de Sangrépine" },
    [66] = { en = "Robes of the Hist", fr = "Robes de l'Hist" },
    [67] = { en = "Shadow Walker", fr = "La Marcheuse d'ombres" },
    [68] = { en = "Stygian", fr = "Le Stygien" },
    [69] = { en = "Ranger's Gait", fr = "La Parure de l'éclaireur" },
    [70] = { en = "Seventh Legion Brute", fr = "Brute de la septième Légion" },
    [71] = { en = "Durok's Bane", fr = "Le Fléau de Durok" },
    [72] = { en = "Nikulas' Heavy Armor", fr = "L’Armure lourde de Nikulas" },
    [73] = { en = "Oblivion's Foe", fr = "L’Adversaire d'Oblivion" },
    [74] = { en = "Spectre's Eye", fr = "L’Œil du spectre" },
    [75] = { en = "Torug's Pact", fr = "Le Pacte de Torug" },
    [76] = { en = "Robes of Alteration Mastery", fr = "Les Robes de maîtrise de transformation" },
    [77] = { en = "Crusader", fr = "Le Croisé" },
    [78] = { en = "Hist Bark", fr = "L’Écorce d'Hist" },
    [79] = { en = "Willow's Path", fr = "Le Sentier des saules" },
    [80] = { en = "Hunding's Rage", fr = "La Rage de Hunding" },
    [81] = { en = "Song of Lamae", fr = "Le Chant de Lamae" },
    [82] = { en = "Alessia's Bulwark", fr = "Le Rempart d'Alessia" },
    [83] = { en = "Elf Bane", fr = "Le Fléau des Elfes" },
    [84] = { en = "Orgnum's Scales", fr = "Les Écailles d'Orgnum" },
    [85] = { en = "Almalexia's Mercy", fr = "La Clémence d'Almalexia" },
    [86] = { en = "Queen's Elegance", fr = "Élégance de la reine" },
    [87] = { en = "Eyes of Mara", fr = "Les Yeux de Mara" },
    [88] = { en = "Robes of Destruction Mastery", fr = "Les Robes de maîtrise de la destruction" },
    [89] = { en = "Sentry", fr = "La Sentinelle" },
    [90] = { en = "Senche's Bite", fr = "Morsure de senche" },
    [91] = { en = "Oblivion's Edge", fr = "Le Tranchant d'Oblivion" },
    [92] = { en = "Kagrenac's Hope", fr = "L’Espoir de Kagrenac" },
    [93] = { en = "Storm Knight's Plate", fr = "L’Armure de plate du chevalier-tempête" },
    [94] = { en = "Meridia's Blessed Armor", fr = "Armure bénie de Méridia" },
    [95] = { en = "Shalidor's Curse", fr = "La Malédiction de Shalidor" },
    [96] = { en = "Armor of Truth", fr = "L’Armure de vérité" },
    [97] = { en = "The Arch-Mage", fr = "L’Archimage" },
    [98] = { en = "Necropotence", fr = "Nécropotence" },
    [99] = { en = "Salvation", fr = "Le Salut" },
    [100] = { en = "Hawk's Eye", fr = "L’Œil de faucon" },
    [101] = { en = "Affliction", fr = "Affliction" },
    [102] = { en = "Duneripper's Scales", fr = "Écailles de l'éventreur des dunes" },
    [103] = { en = "Magicka Furnace", fr = "Le Fourneau de magie" },
    [104] = { en = "Curse Eater", fr = "Le Mangeur de malédiction" },
    [105] = { en = "Twin Sisters", fr = "Les Sœurs jumelles" },
    [106] = { en = "Wilderqueen's Arch", fr = "Arche de la Reine-nature" },
    [107] = { en = "Wyrd Tree's Blessing", fr = "Bénédiction du Wyrd" },
    [109] = { en = "Light of Cyrodiil", fr = "La Lumière de Cyrodiil" },
    [110] = { en = "Sanctuary", fr = "Le Sanctuaire" },
    [111] = { en = "Ward of Cyrodiil", fr = "La Défense de Cyrodiil" },
    [112] = { en = "Night Terror", fr = "Terreur nocturne" },
    [113] = { en = "Crest of Cyrodiil", fr = "Les Armoiries de Cyrodiil" },
    [114] = { en = "Soulshine", fr = "L’Âme lumineuse" },
    [116] = { en = "The Destruction Suite", fr = "La suite de destruction" },
    [117] = { en = "Relics of the Physician, Ansur", fr = "Les reliques du docteur Ansur" },
    [118] = { en = "Treasures of the Earthforge", fr = "Les Trésors de la Forgeterre" },
    [119] = { en = "Relics of the Rebellion", fr = "Les Reliques de la rébellion" },
    [120] = { en = "Arms of Infernace", fr = "Les Armes d'Infernace" },
    [121] = { en = "Arms of the Ancestors", fr = "Les Armes des ancêtres" },
    [122] = { en = "Ebon Armory", fr = "L’Armurerie d'ébonite" },
    [123] = { en = "Hircine's Veneer", fr = "La Meute d'Hircine" },
    [124] = { en = "The Worm's Raiment", fr = "La Tenue du Ver" },
    [125] = { en = "Wrath of the Imperium", fr = "La Fureur de l'Empire" },
    [126] = { en = "Grace of the Ancients", fr = "La Grâce des anciens" },
    [127] = { en = "Deadly Strike", fr = "La Frappe mortelle" },
    [128] = { en = "Blessing of the Potentates", fr = "La Bénédiction des monarques" },
    [129] = { en = "Vengeance Leech", fr = "Rétribution" },
    [130] = { en = "Eagle Eye", fr = "L’Œil d'aigle" },
    [131] = { en = "Bastion of the Heartland", fr = "Le Bastion du continent" },
    [132] = { en = "Shield of the Valiant", fr = "Le Bouclier du vaillant" },
    [133] = { en = "Buffer of the Swift", fr = "Le Boutoir de rapidité" },
    [134] = { en = "Shroud of the Lich", fr = "Le Suaire de la liche" },
    [135] = { en = "Draugr's Heritage", fr = "L’Héritage du Draugr" },
    [136] = { en = "Immortal Warrior", fr = "Le Guerrier immortel" },
    [137] = { en = "Berserking Warrior", fr = "Le Guerrier furieux" },
    [138] = { en = "Defending Warrior", fr = "Le Guerrier défenseur" },
    [139] = { en = "Wise Mage", fr = "Le Mage avisé" },
    [140] = { en = "Destructive Mage", fr = "Le Mage destructeur" },
    [141] = { en = "Healing Mage", fr = "Le Mage guérisseur" },
    [142] = { en = "Quick Serpent", fr = "Le Serpent rapide" },
    [143] = { en = "Poisonous Serpent", fr = "Le Serpent venimeux" },
    [144] = { en = "Twice-Fanged Serpent", fr = "Le Serpent à deux crocs" },
    [145] = { en = "Way of Fire", fr = "La Voie du feu" },
    [146] = { en = "Way of Air", fr = "La Voie de l'air" },
    [147] = { en = "Way of Martial Knowledge", fr = "La Voie de la connaissance martiale" },
    [148] = { en = "Way of the Arena", fr = "La Voie de l'arène" },
    [155] = { en = "Undaunted Bastion", fr = "Bastion indomptable" },
    [156] = { en = "Undaunted Infiltrator", fr = "Infiltrateur indomptable" },
    [157] = { en = "Undaunted Unweaver", fr = "Détrameur indomptable" },
    [158] = { en = "Embershield", fr = "Bouclier de braise" },
    [159] = { en = "Sunderflame", fr = "Scindeflamme" },
    [160] = { en = "Burning Spellweave", fr = "Le Tramesort ardent" },
    [161] = { en = "Twice-Born Star", fr = "Étoile gémellaire" },
    [162] = { en = "Spawn of Mephala", fr = "L’Engeance de Méphala" },
    [163] = { en = "Bloodspawn", fr = "L’Engeance de sang" },
    [164] = { en = "Lord Warden", fr = "Le Seigneur gardien" },
    [165] = { en = "Scourge Harvester", fr = "Moissonneur calamiteux" },
    [166] = { en = "Engine Guardian", fr = "Le Gardien du moteur" },
    [167] = { en = "Nightflame", fr = "La Nocteflamme" },
    [168] = { en = "Nerien'eth", fr = "Nérien'eth" },
    [169] = { en = "Valkyn Skoria", fr = "Valkyn Skoria" },
    [170] = { en = "Maw of the Infernal", fr = "Gueule de l'Infernal" },
    [171] = { en = "Eternal Warrior", fr = "L’Éternel Guerrier" },
    [172] = { en = "Infallible Mage", fr = "L’Infaillible Mage" },
    [173] = { en = "Vicious Serpent", fr = "Le Cruel Serpent" },
    [176] = { en = "Noble's Conquest", fr = "Le Butin du noble" },
    [177] = { en = "Redistributor", fr = "Redistributeur" },
    [178] = { en = "Armor Master", fr = "Maître armurier" },
    [179] = { en = "Black Rose", fr = "La Rose noire" },
    [180] = { en = "Powerful Assault", fr = "L’Assaut puissant" },
    [181] = { en = "Meritorious Service", fr = "Le Service émérite" },
    [183] = { en = "Molag Kena", fr = "Molag Kena" },
    [184] = { en = "Brands of Imperium", fr = "Les Marques d'Imperium" },
    [185] = { en = "Spell Power Cure", fr = "Puissance curative" },
    [186] = { en = "Jolting Arms", fr = "Les Armes de la décharge" },
    [187] = { en = "Swamp Raider", fr = "Pilleur du marais" },
    [188] = { en = "Storm Master", fr = "La Maîtrise de la tempête" },
    [190] = { en = "Scathing Mage", fr = "Le Mage brûlant" },
    [193] = { en = "Overwhelming Surge", fr = "L’Élan de Suprématie" },
    [194] = { en = "Combat Physician", fr = "Le Médecin de terrain" },
    [195] = { en = "Sheer Venom", fr = "Le Venin absolu" },
    [196] = { en = "Leeching Plate", fr = "La Plaque sangsue" },
    [197] = { en = "Tormentor", fr = "Le Tortionnaire" },
    [198] = { en = "Essence Thief", fr = "Voleur d'essence" },
    [199] = { en = "Shield Breaker", fr = "Brise-bouclier" },
    [200] = { en = "Phoenix", fr = "Le Phénix" },
    [201] = { en = "Reactive Armor", fr = "Armure réactive" },
    [204] = { en = "Endurance", fr = "Endurance" },
    [205] = { en = "Willpower", fr = "Volonté" },
    [206] = { en = "Agility", fr = "Agilité" },
    [207] = { en = "Law of Julianos", fr = "Loi de Julianos" },
    [208] = { en = "Trial by Fire", fr = "Épreuve du feu" },
    [210] = { en = "Mark of the Pariah", fr = "La Marque du Paria" },
    [211] = { en = "Permafrost", fr = "Le Permafrost" },
    [212] = { en = "Briarheart", fr = "Roncecœur" },
    [213] = { en = "Glorious Defender", fr = "Défense glorieuse" },
    [214] = { en = "Para Bellum", fr = "Para Bellum" },
    [215] = { en = "Elemental Succession", fr = "Succession élémentaire" },
    [216] = { en = "Hunt Leader", fr = "Le Chef de la chasse" },
    [217] = { en = "Winterborn", fr = "Nédhiver" },
    [218] = { en = "Trinimac's Valor", fr = "La Valeur de Trinimac" },
    [219] = { en = "Morkuldin", fr = "Morkuldin" },
    [224] = { en = "Tava's Favor", fr = "La Faveur de Tava" },
    [225] = { en = "Clever Alchemist", fr = "L’Alchimiste astucieux" },
    [226] = { en = "Eternal Hunt", fr = "La Chasse éternelle" },
    [227] = { en = "Bahraha's Curse", fr = "La Malédiction de Bahraha" },
    [228] = { en = "Syvarra's Scales", fr = "Les Écailles de Syvarra" },
    [229] = { en = "Twilight Remedy", fr = "Le Remède du crépuscule" },
    [230] = { en = "Moondancer", fr = "Danselune" },
    [231] = { en = "Lunar Bastion", fr = "Bastion lunaire" },
    [232] = { en = "Roar of Alkosh", fr = "Le Rugissement d'Alkosh" },
    [234] = { en = "Marksman's Crest", fr = "Emblème du tireur d'élite" },
    [235] = { en = "Robes of Transmutation", fr = "Robes de transmutation" },
    [236] = { en = "Vicious Death", fr = "Mort cruelle" },
    [237] = { en = "Leki's Focus", fr = "Focalisation de Léki" },
    [238] = { en = "Fasalla's Guile", fr = "Perfidie de Fasalla" },
    [239] = { en = "Warrior's Fury", fr = "Furie du Guerrier" },
    [240] = { en = "Kvatch Gladiator", fr = "Le gladiateur de Kvatch" },
    [241] = { en = "Varen's Legacy", fr = "L’Héritage de Varen" },
    [242] = { en = "Pelinal's Wrath", fr = "Le Courroux de Pélinal" },
    [243] = { en = "Hide of Morihaus", fr = "La Peau de Morihaus" },
    [244] = { en = "Flanking Strategist", fr = "Le Stratège du débordement" },
    [245] = { en = "Sithis' Touch", fr = "La Caresse de Sithis" },
    [246] = { en = "Galerion's Revenge", fr = "La vengeance de Galérion" },
    [247] = { en = "Vicecanon of Venom", fr = "Le vice-chanoine du venin" },
    [248] = { en = "Thews of the Harbinger", fr = "Les muscles du héraut" },
    [253] = { en = "Imperial Physique", fr = "Le physique impérial" },
    [256] = { en = "Mighty Chudan", fr = "Le Gros Chudan" },
    [257] = { en = "Velidreth", fr = "Velidreth" },
    [258] = { en = "Amber Plasm", fr = "Plasme ambré" },
    [259] = { en = "Heem-Jas' Retribution", fr = "Châtiment d'Heem-Jas" },
    [260] = { en = "Aspect of Mazzatun", fr = "Aspect de Mazzatun" },
    [261] = { en = "Gossamer", fr = "Diaphane" },
    [262] = { en = "Widowmaker", fr = "Deuil" },
    [263] = { en = "Hand of Mephala", fr = "Main de Méphala" },
    [265] = { en = "Shadowrend", fr = "Taillombre" },
    [266] = { en = "Kra'gh", fr = "Kra'gh" },
    [267] = { en = "Swarm Mother", fr = "La Mère de la nuée" },
    [268] = { en = "Sentinel of Rkugamz", fr = "La sentinelle de Rkugamz" },
    [269] = { en = "Chokethorn", fr = "La Ronce étouffeuse" },
    [270] = { en = "Slimecraw", fr = "Rampefange" },
    [271] = { en = "Sellistrix", fr = "Sellistrix" },
    [272] = { en = "Infernal Guardian", fr = "Gardien infernal" },
    [273] = { en = "Ilambris", fr = "Ilambris" },
    [274] = { en = "Iceheart", fr = "Cœur-de-glace" },
    [275] = { en = "Stormfist", fr = "Poigne-tempête" },
    [276] = { en = "Tremorscale", fr = "Tremblécaille" },
    [277] = { en = "Pirate Skeleton", fr = "Pirate squelettique" },
    [278] = { en = "The Troll King", fr = "Le roi des Trolls" },
    [279] = { en = "Selene", fr = "Sélène" },
    [280] = { en = "Grothdarr", fr = "Grothdarr" },
    [281] = { en = "Armor of the Trainee", fr = "Armure du débutant" },
    [282] = { en = "Vampire Cloak", fr = "Cape du vampire" },
    [283] = { en = "Sword-Singer", fr = "Chante-épée" },
    [284] = { en = "Order of Diagna", fr = "Ordre de Diagna" },
    [285] = { en = "Vampire Lord", fr = "Seigneur vampire" },
    [286] = { en = "Spriggan's Thorns", fr = "Ronces du spriggan" },
    [287] = { en = "Green Pact", fr = "Le Pacte Vert" },
    [288] = { en = "Beekeeper's Gear", fr = "Harnachement de l'apiculteur" },
    [289] = { en = "Spinner's Garments", fr = "Tenue du trameur" },
    [290] = { en = "Skooma Smuggler", fr = "Traficant de skouma" },
    [291] = { en = "Shalk Exoskeleton", fr = "Exosquelette de shalk" },
    [292] = { en = "Mother's Sorrow", fr = "Chagrin maternel" },
    [293] = { en = "Plague Doctor", fr = "Médecin de la peste" },
    [294] = { en = "Ysgramor's Birthright", fr = "Héritage d'Ysgramor" },
    [295] = { en = "Jailbreaker", fr = "L’Évasion" },
    [296] = { en = "Spelunker", fr = "Spéléologue" },
    [297] = { en = "Spider Cultist Cowl", fr = "Capuchon de l'adepte de l'Araignée" },
    [298] = { en = "Light Speaker", fr = "Orateur lumineux" },
    [299] = { en = "Toothrow", fr = "La Rangée de dents" },
    [300] = { en = "Netch's Touch", fr = "Toucher du netch" },
    [301] = { en = "Strength of the Automaton", fr = "Force de l'automate" },
    [302] = { en = "Leviathan", fr = "Le Léviathan" },
    [303] = { en = "Lamia's Song", fr = "Chant de la Lamie" },
    [304] = { en = "Medusa", fr = "La Méduse" },
    [305] = { en = "Treasure Hunter", fr = "Le chasseur de trésors" },
    [307] = { en = "Draugr Hulk", fr = "Le Draugr colossal" },
    [308] = { en = "Bone Pirate's Tatters", fr = "Haillons du pirate squelettique" },
    [309] = { en = "Knight-errant's Mail", fr = "Maille de chevalier errant" },
    [310] = { en = "Sword Dancer", fr = "La Danse des épées" },
    [311] = { en = "Rattlecage", fr = "Le Provocateur" },
    [313] = { en = "Titanic Cleave", fr = "Le Fendoir tinanesque" },
    [314] = { en = "Puncturing Remedy", fr = "Le Remède perforant" },
    [315] = { en = "Stinging Slashes", fr = "Entailles cuisantes" },
    [316] = { en = "Caustic Arrow", fr = "Flèche caustique" },
    [317] = { en = "Destructive Impact", fr = "Impact destructeur" },
    [318] = { en = "Grand Rejuvenation", fr = "Grand Rajeunissement" },
    [320] = { en = "War Maiden", fr = "La Vierge guerrière" },
    [321] = { en = "Defiler", fr = "Profanateur" },
    [322] = { en = "Warrior-Poet", fr = "Le Guerrier-Poète" },
    [323] = { en = "Assassin's Guile", fr = "La Duplicité de l'assassin" },
    [324] = { en = "Daedric Trickery", fr = "La Tromperie daedrique" },
    [325] = { en = "Shacklebreaker", fr = "Le Brise-entraves" },
    [326] = { en = "Vanguard's Challenge", fr = "Défi de l'avant-garde" },
    [327] = { en = "Coward's Gear", fr = "Barda du couard" },
    [328] = { en = "Knight Slayer", fr = "Tueur de chevalier" },
    [329] = { en = "Wizard's Riposte", fr = "Riposte du sorcier" },
    [330] = { en = "Automated Defense", fr = "La Défense automatique" },
    [331] = { en = "War Machine", fr = "La machine de guerre" },
    [332] = { en = "Master Architect", fr = "Le maître architecte" },
    [333] = { en = "Inventor's Guard", fr = "La Garde de l'inventeur" },
    [334] = { en = "Impregnable Armor", fr = "Armure imprenable" },
    [335] = { en = "Draugr's Rest", fr = "Le Repos du Draugr" },
    [336] = { en = "Pillar of Nirn", fr = "Pilier de Nirn" },
    [337] = { en = "Ironblood", fr = "Sang de fer" },
    [338] = { en = "Flame Blossom", fr = "Fleur de feu" },
    [339] = { en = "Blooddrinker", fr = "La Buveur de sang" },
    [340] = { en = "Hagraven's Garden", fr = "Jardin de la harfreuse" },
    [341] = { en = "Earthgore", fr = "Sangreterre" },
    [342] = { en = "Domihaus", fr = "Domihaus" },
    [343] = { en = "Caluurion's Legacy", fr = "L’Héritage de Caluurion" },
    [344] = { en = "Trappings of Invigoration", fr = "Apparence de vivification" },
    [345] = { en = "Ulfnor's Favor", fr = "La Faveur d'Ulfnor" },
    [346] = { en = "Jorvuld's Guidance", fr = "Le Conseil de Jorvuld" },
    [347] = { en = "Plague Slinger", fr = "Lance-peste" },
    [348] = { en = "Curse of Doylemish", fr = "La Malédiction de Doylemish" },
    [349] = { en = "Thurvokun", fr = "Thurvokun" },
    [350] = { en = "Zaan", fr = "Zaan" },
    [351] = { en = "Innate Axiom", fr = "Axiome inné" },
    [352] = { en = "Fortified Brass", fr = "Airain fortifié" },
    [353] = { en = "Mechanical Acuity", fr = "Acuité mécanique" },
    [354] = { en = "Mad Tinkerer", fr = "Bricoleur fou" },
    [355] = { en = "Unfathomable Darkness", fr = "Ténèbres insondables" },
    [356] = { en = "Livewire", fr = "Haute tension" },
    [357] = { en = "Perfected Disciplined Slash", fr = "Entaille disciplinée perfectionnée" },
    [358] = { en = "Perfected Defensive Position", fr = "Position défensive perfectionnée" },
    [359] = { en = "Perfected Chaotic Whirlwind", fr = "Tourbillon chaotique perfectionné" },
    [360] = { en = "Perfected Piercing Spray", fr = "Jaillissement perforant perfectionné" },
    [361] = { en = "Perfected Concentrated Force", fr = "Force concentrée perfectionnée" },
    [362] = { en = "Perfected Timeless Blessing", fr = "Bénédiction intemporelle perfectionnée" },
    [363] = { en = "Disciplined Slash", fr = "Entaille disciplinée" },
    [364] = { en = "Defensive Position", fr = "Position défensive" },
    [365] = { en = "Chaotic Whirlwind", fr = "Tourbillon chaotique" },
    [366] = { en = "Piercing Spray", fr = "Jaillissement perforant" },
    [367] = { en = "Concentrated Force", fr = "Force concentrée" },
    [368] = { en = "Timeless Blessing", fr = "Bénédiction intemporelle" },
    [369] = { en = "Merciless Charge", fr = "La Charge impitoyable" },
    [370] = { en = "Rampaging Slash", fr = "L’Entaille ravageuse" },
    [371] = { en = "Cruel Flurry", fr = "Le Déluge cruel" },
    [372] = { en = "Thunderous Volley", fr = "La Volée tonitruante" },
    [373] = { en = "Crushing Wall", fr = "Le Mur écrasant" },
    [374] = { en = "Precise Regeneration", fr = "La Régénération précise" },
    [380] = { en = "Prophet's", fr = "L’Ensemble du Prophète" },
    [381] = { en = "Broken Soul", fr = "L’Âme brisée" },
    [382] = { en = "Grace of Gloom", fr = "La Gracieuse mélancolie" },
    [383] = { en = "Gryphon's Ferocity", fr = "La Férocité du griffon" },
    [384] = { en = "Wisdom of Vanus", fr = "La Sagesse de Vanus" },
    [385] = { en = "Adept Rider", fr = "L’Adepte cavalier" },
    [386] = { en = "Sload's Semblance", fr = "L’Aspect du Sload" },
    [387] = { en = "Nocturnal's Favor", fr = "Faveur de Nocturne" },
    [388] = { en = "Aegis of Galenwe", fr = "L’Égide de Galenwe" },
    [389] = { en = "Arms of Relequen", fr = "Les Armes de Relequen" },
    [390] = { en = "Mantle of Siroria", fr = "Le Manteau de Siroria" },
    [391] = { en = "Vestment of Olorime", fr = "La Vêture d'Olorimë" },
    [392] = { en = "Perfected Aegis of Galenwe", fr = "L’Égide de Galenwe perfectionnée" },
    [393] = { en = "Perfected Arms of Relequen", fr = "Armes de Relequen perfectionnées" },
    [394] = { en = "Perfected Mantle of Siroria", fr = "Le Manteau de Siroria perfectionné" },
    [395] = { en = "Perfected Vestment of Olorime", fr = "La vêture d'Olorimë perfectionnée" },
    [397] = { en = "Balorgh", fr = "Balorgh" },
    [398] = { en = "Vykosa", fr = "Vykosa" },
    [399] = { en = "Hanu's Compassion", fr = "La Compassion de Hanu" },
    [400] = { en = "Blood Moon", fr = "La Lune de sang" },
    [401] = { en = "Haven of Ursus", fr = "Le Havre d'Ursus" },
    [402] = { en = "Moon Hunter", fr = "Le Chasseur lunaire" },
    [403] = { en = "Savage Werewolf", fr = "Le Loup-garou sauvage" },
    [404] = { en = "Jailer's Tenacity", fr = "La Ténacité du Geôlier" },
    [405] = { en = "Bright-Throat's Boast", fr = "La Vantardise de Vive-Gorge" },
    [406] = { en = "Dead-Water's Guile", fr = "La Duplicité d'Aiguemortes" },
    [407] = { en = "Champion of the Hist", fr = "Le Champion de l'Hist" },
    [408] = { en = "Grave-Stake Collector", fr = "Collectionneur de marqueurs funéraires" },
    [409] = { en = "Naga Shaman", fr = "Le Chaman Naga" },
    [410] = { en = "Might of the Lost Legion", fr = "La Puissance de la Légion perdue" },
    [411] = { en = "Gallant Charge", fr = "Charge vaillante" },
    [412] = { en = "Radial Uppercut", fr = "Uppercut radial" },
    [413] = { en = "Spectral Cloak", fr = "Cape spectrale" },
    [414] = { en = "Virulent Shot", fr = "Tir virulent" },
    [415] = { en = "Wild Impulse", fr = "Impulsion sauvage" },
    [416] = { en = "Mender's Ward", fr = "Garde du soigneur" },
    [417] = { en = "Indomitable Fury", fr = "Fureur indomptable" },
    [418] = { en = "Spell Strategist", fr = "Stratège des sorts" },
    [419] = { en = "Battlefield Acrobat", fr = "Acrobate du champ de bataille" },
    [420] = { en = "Soldier of Anguish", fr = "Soldat de l'angoisse" },
    [421] = { en = "Steadfast Hero", fr = "Héros inébranlable" },
    [422] = { en = "Battalion Defender", fr = "Défense du bataillon" },
    [423] = { en = "Perfected Gallant Charge", fr = "Charge galante perfectionnée" },
    [424] = { en = "Perfected Radial Uppercut", fr = "Uppercut radial perfectionné" },
    [425] = { en = "Perfected Spectral Cloak", fr = "Cape spectrale perfectionnée" },
    [426] = { en = "Perfected Virulent Shot", fr = "Tir virulent perfectionné" },
    [427] = { en = "Perfected Wild Impulse", fr = "Impulsion sauvage perfectionnée" },
    [428] = { en = "Perfected Mender's Ward", fr = "Garde du guérisseur perfectionnée" },
    [429] = { en = "Mighty Glacier", fr = "Le Puissant glacier" },
    [430] = { en = "Tzogvin's Warband", fr = "La Bande de guerre de Tzogvin" },
    [431] = { en = "Icy Conjurer", fr = "L’Invocateur glacial" },
    [432] = { en = "Stonekeeper", fr = "Le Gardien des pierres" },
    [433] = { en = "Frozen Watcher", fr = "L’Observateur glacial" },
    [434] = { en = "Scavenging Demise", fr = "Le Trépas des récupérateurs" },
    [435] = { en = "Auroran's Thunder", fr = "Le Tonnerre aurorien" },
    [436] = { en = "Symphony of Blades", fr = "La Symphonie de lames" },
    [437] = { en = "Coldharbour's Favorite", fr = "Élu de Havreglace" },
    [438] = { en = "Senche-raht's Grit", fr = "La Détermination du senche-raht" },
    [439] = { en = "Vastarie's Tutelage", fr = "La Tutelle de Vastarië" },
    [440] = { en = "Crafty Alfiq", fr = "L’Alfiq rusé" },
    [441] = { en = "Vesture of Darloc Brae", fr = "Le Vêtement de Darloc Brae" },
    [442] = { en = "Call of the Undertaker", fr = "L’Appel du Croque-mort" },
    [443] = { en = "Eye of Nahviintaas", fr = "L’Œil de Nahviintaas" },
    [444] = { en = "False God's Devotion", fr = "Le Dévot du Faux dieu" },
    [445] = { en = "Tooth of Lokkestiiz", fr = "La Dent de Lokkestiiz" },
    [446] = { en = "Claw of Yolnahkriin", fr = "La griffe d’Yolnahkriin" },
    [448] = { en = "Perfected Eye of Nahviintaas", fr = "L’Œil de Nahviintaas perfectionné" },
    [449] = { en = "Perfected False God's Devotion", fr = "Le Dévot du faux dieu perfectionné" },
    [450] = { en = "Perfected Tooth of Lokkestiiz", fr = "Dent de Lokkestiiz perfectionnée" },
    [451] = { en = "Perfected Claw of Yolnahkriin", fr = "La Griffe de Lokkestiiz perfectionnée" },
    [452] = { en = "Hollowfang Thirst", fr = "La Soif du Croc creux" },
    [453] = { en = "Dro'Zakar's Claws", fr = "Griffes de Dro'Zakar" },
    [454] = { en = "Renald's Resolve", fr = "Résolution de Ranald" },
    [455] = { en = "Z'en's Redress", fr = "Redressement de Z'en" },
    [456] = { en = "Azureblight Reaper", fr = "Le Moissonneur de Pestazur" },
    [457] = { en = "Dragon's Defilement", fr = "La Profanation du dragon" },
    [458] = { en = "Grundwulf", fr = "Grundwulf" },
    [459] = { en = "Maarselok", fr = "Maarselok" },
    [465] = { en = "Senchal Defender", fr = "Défenseur de Senchal" },
    [466] = { en = "Marauder's Haste", fr = "La Hâte du Maraudeur" },
    [467] = { en = "Dragonguard Elite", fr = "Élite de la Garde du dragon" },
    [468] = { en = "Daring Corsair", fr = "Le Corsaire intrépide" },
    [469] = { en = "Ancient Dragonguard", fr = "La Garde du dragon antique" },
    [470] = { en = "New Moon Acolyte", fr = "Acolyte de la Nouvelle lune" },
    [471] = { en = "Hiti's Hearth", fr = "Le Foyer de Hiti" },
    [472] = { en = "Titanborn Strength", fr = "La Force de Titan" },
    [473] = { en = "Bani's Torment", fr = "Le Tourment de Bani" },
    [474] = { en = "Draugrkin's Grip", fr = "La Poigne de Draugrien" },
    [475] = { en = "Aegis Caller", fr = "Le Mande-égide" },
    [476] = { en = "Grave Guardian", fr = "Gardien du sépulcre" },
    [478] = { en = "Mother Ciannait", fr = "Mère Ciannait" },
    [479] = { en = "Kjalnar's Nightmare", fr = "Le Cauchemar de Kjalnar" },
    [480] = { en = "Critical Riposte", fr = "Riposte critique" },
    [481] = { en = "Unchained Aggressor", fr = "L’Agresseur déchaîné" },
    [482] = { en = "Dauntless Combatant", fr = "Le Combattant indompté" },
    [487] = { en = "Winter's Respite", fr = "Répit de l'hiver" },
    [488] = { en = "Venomous Smite", fr = "Châtiment venimeux" },
    [489] = { en = "Eternal Vigor", fr = "Vigueur éternelle" },
    [490] = { en = "Stuhn's Favor", fr = "La Faveur de Stuhn" },
    [491] = { en = "Dragon's Appetite", fr = "L’Appétit du dragon" },
    [492] = { en = "Kyne's Wind", fr = "Le Vent de Kyne" },
    [493] = { en = "Perfected Kyne's Wind", fr = "Le Vent de Kyne perfectionné" },
    [494] = { en = "Vrol's Command", fr = "Commandement de Vrol" },
    [495] = { en = "Perfected Vrol's Command", fr = "Le Commandement de Vrol perfectionné" },
    [496] = { en = "Roaring Opportunist", fr = "L’Opportuniste rugissant" },
    [497] = { en = "Perfected Roaring Opportunist", fr = "L’Opportuniste rugissant perfectionné" },
    [498] = { en = "Yandir's Might", fr = "La Puissance d’Yandir" },
    [499] = { en = "Perfected Yandir's Might", fr = "La Puissance d’Yandir perfectionnée" },
    [501] = { en = "Thrassian Stranglers", fr = "Les Étrangleurs thrassiens" },
    [503] = { en = "Ring of the Wild Hunt", fr = "Anneau de la Chasse sauvage" },
    [505] = { en = "Torc of Tonal Constancy", fr = "Le Torque de constance tonale" },
    [506] = { en = "Spell Parasite", fr = "Le Parasite magique" },
    [513] = { en = "Talfyg's Treachery", fr = "La Traîtrise de Talfyg" },
    [514] = { en = "Unleashed Terror", fr = "Terreur déchaînée" },
    [515] = { en = "Crimson Twilight", fr = "Le Crépuscule écarlate" },
    [516] = { en = "Elemental Catalyst", fr = "Catalyseur élémentaire" },
    [517] = { en = "Kraglen's Howl", fr = "Hurlement de Kraglen" },
    [518] = { en = "Arkasis's Genius", fr = "Génie d'Arkasis" },
    [519] = { en = "Snow Treaders", fr = "L’Arpenteurs de neige" },
    [520] = { en = "Malacath's Band of Brutality", fr = "La Bande de brutalité de Malacath" },
    [521] = { en = "Bloodlord's Embrace", fr = "L’Étreinte du Seigneur de sang" },
    [522] = { en = "Perfected Merciless Charge", fr = "Charge impitoyable perfectionnée" },
    [523] = { en = "Perfected Rampaging Slash", fr = "Entaille ravageuse perfectionnée" },
    [524] = { en = "Perfected Cruel Flurry", fr = "Le Déluge cruel perfectionné" },
    [525] = { en = "Perfected Thunderous Volley", fr = "Volée tonitruante perfectionnée" },
    [526] = { en = "Perfected Crushing Wall", fr = "Mur écrasant perfectionné" },
    [527] = { en = "Perfected Precise Regeneration", fr = "Régénération précise perfectionnée" },
    [528] = { en = "Perfected Titanic Cleave", fr = "Fendoir titanesque perfectionné" },
    [529] = { en = "Perfected Puncturing Remedy", fr = "Remède perforant perfectionné" },
    [530] = { en = "Perfected Stinging Slashes", fr = "Entailles cuisantes perfectionnées" },
    [531] = { en = "Perfected Caustic Arrow", fr = "Flèche caustique perfectionnée" },
    [532] = { en = "Perfected Destructive Impact", fr = "Impact destructeur perfectionné" },
    [533] = { en = "Perfected Grand Rejuvenation", fr = "Grand rajeunissement perfectionné" },
    [534] = { en = "Stone Husk", fr = "L’Enveloppe de pierre" },
    [535] = { en = "Lady Thorn", fr = "La Dame Ronce" },
    [536] = { en = "Radiant Bastion", fr = "Le Bastion radieux" },
    [537] = { en = "Voidcaller", fr = "Le Mande-vide" },
    [538] = { en = "Witch-Knight's Defiance", fr = "La Défiance du Chevalier-Sorcière" },
    [539] = { en = "Red Eagle's Fury", fr = "La Fureur de l'Aigle rouge" },
    [540] = { en = "Legacy of Karth", fr = "L’Héritage de Karth" },
    [541] = { en = "Aetherial Ascension", fr = "L’Ascension aéthérienne" },
    [542] = { en = "Hex Siphon", fr = "Siphon de la malédiction" },
    [543] = { en = "Pestilent Host", fr = "Hôte pestilentiel" },
    [544] = { en = "Explosive Rebuke", fr = "Camouflet explosif" },
    [557] = { en = "Executioner's Blade", fr = "Lame du bourreau" },
    [558] = { en = "Void Bash", fr = "Percussion du vide" },
    [559] = { en = "Frenzied Momentum", fr = "L’Élan frénétique" },
    [560] = { en = "Point-Blank Snipe", fr = "Tir à Bout portant" },
    [561] = { en = "Wrath of Elements", fr = "Courroux des éléments" },
    [562] = { en = "Force Overflow", fr = "Le Débordement de force" },
    [563] = { en = "Perfected Executioner's Blade", fr = "La Lame du bourreau perfectionnée" },
    [564] = { en = "Perfected Void Bash", fr = "La Percussion du Vide perfectionnée" },
    [565] = { en = "Perfected Frenzied Momentum", fr = "L’Élan frénétique perfectionné" },
    [566] = { en = "Perfected Point-Blank Snipe", fr = "Le Tir de précision à bout portant perfectionné" },
    [567] = { en = "Perfected Wrath of Elements", fr = "Le Courroux des éléments perfectionné" },
    [568] = { en = "Perfected Force Overflow", fr = "Le Débordement de force perfectionné" },
    [569] = { en = "True-Sworn Fury", fr = "Furie du Fidèle" },
    [570] = { en = "Kinras's Wrath", fr = "Colère de Kinras" },
    [571] = { en = "Drake's Rush", fr = "Ruée du dragon" },
    [572] = { en = "Unleashed Ritualist", fr = "Ritualiste déchaîné" },
    [573] = { en = "Dagon's Dominion", fr = "Domaine de Dagon" },
    [574] = { en = "Foolkiller's Ward", fr = "Garde de Follicide" },
    [575] = { en = "Ring of the Pale Order", fr = "L’anneau de l'Ordre pâle" },
    [576] = { en = "Pearls of Ehlnofey", fr = "Les Perles des Ehlnofey" },
    [577] = { en = "Encratis's Behemoth", fr = "Béhémoth d'Encratis" },
    [578] = { en = "Baron Zaudrus", fr = "Le baron Zaudrus" },
    [579] = { en = "Frostbite", fr = "Engelure" },
    [580] = { en = "Deadlands Assassin", fr = "L’assassin des Terres mortes" },
    [581] = { en = "Bog Raider", fr = "Le Pillard du marais" },
    [582] = { en = "Hist Whisperer", fr = "Le Complice de l'Hist" },
    [583] = { en = "Heartland Conqueror", fr = "Le Conquérant de la Patrie" },
    [584] = { en = "Diamond's Victory", fr = "La Victoire du Diamant" },
    [585] = { en = "Saxhleel Champion", fr = "Le Champion des Saxhleel" },
    [586] = { en = "Sul-Xan's Torment", fr = "Le Tourment des Sul-Xan" },
    [587] = { en = "Bahsei's Mania", fr = "La Folie de Bahsei" },
    [588] = { en = "Stone-Talker's Oath", fr = "Le Serment du Parlepierre" },
    [589] = { en = "Perfected Saxhleel Champion", fr = "Le Champion des Saxhleel perfectionné" },
    [590] = { en = "Perfected Sul-Xan's Torment", fr = "Le Tourment des Sul-Xan perfectionné" },
    [591] = { en = "Perfected Bahsei's Mania", fr = "La Folie de Bahsei perfectionnée" },
    [592] = { en = "Perfected Stone-Talker's Oath", fr = "Le Serment du Parlepierre perfectionné" },
    [593] = { en = "Gaze of Sithis", fr = "Le Regard de Sithis" },
    [594] = { en = "Harpooner's Wading Kilt", fr = "Kilt de plongée de harponneur" },
    [596] = { en = "Death Dealer's Fete", fr = "La Fête du porteur de mort" },
    [597] = { en = "Shapeshifter's Chain", fr = "Chaîne du changeforme" },
    [598] = { en = "Zoal the Ever-Wakeful", fr = "Zoal l'Éveillé" },
    [599] = { en = "Immolator Charr", fr = "L’immolateur Charr" },
    [600] = { en = "Glorgoloch the Destroyer", fr = "Glorgoloch le destructeur" },
    [602] = { en = "Crimson Oath's Rive", fr = "Déchirure du Serment écarlate" },
    [603] = { en = "Scorion's Feast", fr = "Festin de Scorion" },
    [604] = { en = "Rush of Agony", fr = "Élan d'agonie" },
    [605] = { en = "Silver Rose Vigil", fr = "Veille de la Rose d'argent" },
    [606] = { en = "Thunder Caller", fr = "Mande-tonnerre" },
    [607] = { en = "Grisly Gourmet", fr = "Gourmet sinistre" },
    [608] = { en = "Prior Thierric", fr = "Prieur Thierric" },
    [609] = { en = "Magma Incarnate", fr = "Le Magma Incarné" },
    [610] = { en = "Wretched Vitality", fr = "Vitalité perdue" },
    [611] = { en = "Deadlands Demolisher", fr = "Démolisseur des Terres mortes" },
    [612] = { en = "Iron Flask", fr = "Flasque de fer" },
    [613] = { en = "Eye of the Grasp", fr = "Œil de l'Étreinte" },
    [614] = { en = "Hexos' Ward", fr = "La Garde d'Hexos" },
    [615] = { en = "Kynmarcher's Cruelty", fr = "Cruauté de la Kynmarcheuse" },
    [616] = { en = "Dark Convergence", fr = "Convergence noire" },
    [617] = { en = "Plaguebreak", fr = "Brise-peste" },
    [618] = { en = "Hrothgar's Chill", fr = "Frisson de Hrothgar" },
    [619] = { en = "Maligalig's Maelstrom", fr = "Le Maelström de Marigalig" },
    [620] = { en = "Gryphon's Reprisal", fr = "Représailles de griffon" },
    [621] = { en = "Glacial Guardian", fr = "Gardien glacial" },
    [622] = { en = "Turning Tide", fr = "Marée renversée" },
    [623] = { en = "Storm-Cursed's Revenge", fr = "Vengeance maudite par l'orage" },
    [624] = { en = "Spriggan's Vigor", fr = "Vigueur du spriggan" },
    [625] = { en = "Markyn Ring of Majesty", fr = "L’Anneau de majesté de Markyn" },
    [626] = { en = "Belharza's Band", fr = "La Bande de Belharza" },
    [627] = { en = "Spaulder of Ruin", fr = "La Spallière de ruine" },
    [629] = { en = "Rallying Cry", fr = "Le Cri de ralliement" },
    [630] = { en = "Hew and Sunder", fr = "Tranche et Taille" },
    [631] = { en = "Enervating Aura", fr = "Aura affaiblissante" },
    [632] = { en = "Kargaeda", fr = "Kargaeda" },
    [633] = { en = "Nazaray", fr = "Nazaray" },
    [634] = { en = "Nunatak", fr = "Nunatak" },
    [635] = { en = "Lady Malygda", fr = "La dame Malygda" },
    [636] = { en = "Baron Thirsk", fr = "Le baron Thirsk" },
    [640] = { en = "Order's Wrath", fr = "Fureur de l'Ordre" },
    [641] = { en = "Serpent's Disdain", fr = "Dédain du serpent" },
    [642] = { en = "Druid's Braid", fr = "La Tresse druidique" },
    [643] = { en = "Blessing of High Isle", fr = "Bénédiction de l'Île-Haute" },
    [644] = { en = "Steadfast's Mettle", fr = "Endurance des Inébranlables" },
    [645] = { en = "Systres' Scowl", fr = "La Grimace des Systres" },
    [646] = { en = "Whorl of the Depths", fr = "Le Tourbillon des profondeurs" },
    [647] = { en = "Coral Riptide", fr = "Lame de corail" },
    [648] = { en = "Pearlescent Ward", fr = "Garde perlescente" },
    [649] = { en = "Pillager's Profit", fr = "Le Profit du pillard" },
    [650] = { en = "Perfected Pillager's Profit", fr = "Le Profit du pillard perfectionné" },
    [651] = { en = "Perfected Pearlescent Ward", fr = "La Garde perlescente perfectionnée" },
    [652] = { en = "Perfected Coral Riptide", fr = "La Lame de corail perfectionnée" },
    [653] = { en = "Perfected Whorl of the Depths", fr = "Tourbillon des profondeurs perfectionné" },
    [654] = { en = "Mora's Whispers", fr = "Murmures de Mora" },
    [655] = { en = "Dov-rha Sabatons", fr = "Solerets de Dov-rha" },
    [656] = { en = "Lefthander's Aegis Belt", fr = "Ceinture de l'égide du gaucher" },
    [657] = { en = "Sea-Serpent's Coil", fr = "Anneau de serpent de mer" },
    [658] = { en = "Oakensoul Ring", fr = "Anneau d'âme du chêne" },
    [660] = { en = "Deeproot Zeal", fr = "Le Zèle de Longuesouche" },
    [661] = { en = "Stone's Accord", fr = "L’Accord de pierre" },
    [662] = { en = "Rage of the Ursauk", fr = "La Rage de l'Ursauk" },
    [663] = { en = "Pangrit Denmother", fr = "La Couveuse pangrit" },
    [664] = { en = "Grave Inevitability", fr = "Inévitabilité funèbre" },
    [665] = { en = "Phylactery's Grasp", fr = "Emprise du phylactère" },
    [666] = { en = "Archdruid Devyric", fr = "L’archidruide Devyric" },
    [667] = { en = "Euphotic Gatekeeper", fr = "Le Portier euphotique" },
    [668] = { en = "Languor of Peryite", fr = "La Langueur de Péryite" },
    [669] = { en = "Nocturnal's Ploy", fr = "Le Stratagème de Nocturne" },
    [670] = { en = "Mara's Balm", fr = "Baume de Mara" },
    [671] = { en = "Back-Alley Gourmand", fr = "Le Gourmet des ruelles" },
    [672] = { en = "Phoenix Moth Theurge", fr = "Papillon phénix théurge" },
    [673] = { en = "Bastion of the Draoife", fr = "Le bastion du Draoife" },
    [674] = { en = "Faun's Lark Cladding", fr = "Barde de farce de faune" },
    [675] = { en = "Stormweaver's Cavort", fr = "Gambade de la Tisseuse de foudre" },
    [676] = { en = "Syrabane's Ward", fr = "La Garde de Syrabane" },
    [677] = { en = "Chimera's Rebuke", fr = "La Rebuffade de la chimère" },
    [678] = { en = "Old Growth Brewer", fr = "Le Brasseur de la Vieille croissance" },
    [679] = { en = "Claw of the Forest Wraith", fr = "La Griffe du spectre forestier" },
    [680] = { en = "Ritemaster's Bond", fr = "Lien du maître des rites" },
    [681] = { en = "Nix-Hound's Howl", fr = "Hurlement du chien nix" },
    [682] = { en = "Telvanni Enforcer", fr = "Le Défenseur telvanni" },
    [683] = { en = "Roksa the Warped", fr = "Roksa le Déformé" },
    [684] = { en = "Runecarver's Blaze", fr = "Tailleur de rune éclatant" },
    [685] = { en = "Apocryphal Inspiration", fr = "Inspiration apocryphale" },
    [686] = { en = "Abyssal Brace", fr = "Abîmes" },
    [687] = { en = "Ozezan the Inferno", fr = "Ozezan l'Infernal" },
    [688] = { en = "Snake in the Stars", fr = "Le Serpent dans les étoiles" },
    [689] = { en = "Shell Splitter", fr = "Brise-carapace" },
    [690] = { en = "Judgment of Akatosh", fr = "Le Jugement d'Akatosh" },
    [691] = { en = "Cryptcanon Vestments", fr = "Vêtements du Chanoine de la crypte" },
    [692] = { en = "Esoteric Environment Greaves", fr = "Grèves d'environnement ésotérique" },
    [693] = { en = "Torc of the Last Ayleid King", fr = "Le torque du Dernier roi ayléide" },
    [694] = { en = "Velothi Ur-Mage's Amulet", fr = "L’Amulette d'ur-mage Vélothi" },
    [695] = { en = "Shattered Fate", fr = "Le Destin brisé" },
    [696] = { en = "Telvanni Efficiency", fr = "L’Efficacité Telvanni" },
    [697] = { en = "Seeker Synthesis", fr = "La Synthèse du chercheur" },
    [698] = { en = "Vivec's Duality", fr = "La Dualité de Vivec" },
    [699] = { en = "Camonna Tong", fr = "La Camonna Tong" },
    [700] = { en = "Adamant Lurker", fr = "Le Rôdeur adamant" },
    [701] = { en = "Peace and Serenity", fr = "La Paix et Sérénité" },
    [702] = { en = "Ansuul's Torment", fr = "Le Tourment d'Ansuul" },
    [703] = { en = "Test of Resolve", fr = "L’Épreuve de détermination" },
    [704] = { en = "Transformative Hope", fr = "L’Espoir transformatif" },
    [705] = { en = "Perfected Transformative Hope", fr = "L’Espoir transformatif perfectionné" },
    [706] = { en = "Perfected Test of Resolve", fr = "L’Épreuve de détermination perfectionnée" },
    [707] = { en = "Perfected Ansuul's Torment", fr = "Le Tourment d'Ansuul perfectionné" },
    [708] = { en = "Perfected Peace and Serenity", fr = "La Paix et Sérénité perfectionnées" },
    [711] = { en = "Colovian Highlands General", fr = "Le général des hautes terres coloviennes" },
    [712] = { en = "Jerall Mountains Warchief", fr = "Le chef de guerre des monts Jerall" },
    [713] = { en = "Nibenay Bay Battlereeve", fr = "Le haut commissaire de la baie Nibenaise" },
    [722] = { en = "Reawakened Hierophant", fr = "Le Hiérophante réveillé" },
    [723] = { en = "Basalt-Blooded Warrior", fr = "Le Guerrier aux veines de basalte" },
    [724] = { en = "Nobility in Decay", fr = "Corruption noble" },
    [726] = { en = "Soulcleaver", fr = "Tranche-âme" },
    [727] = { en = "Monolith of Storms", fr = "Le Monolithe des tempêtes" },
    [728] = { en = "Wrathsun", fr = "Colère du soleil" },
    [729] = { en = "Gardener of Seasons", fr = "Jardinier des saisons" },
    [730] = { en = "Cinders of Anthelmir", fr = "Les Cendres d'Anthelmir" },
    [731] = { en = "Sluthrug's Hunger", fr = "La Faim de Sluthrug" },
    [732] = { en = "Black-Glove Grounding", fr = "L’Ancrage du Gant noir" },
    [734] = { en = "Anthelmir's Construct", fr = "L’Assemblage d'Anthelmir" },
    [735] = { en = "Blind Path Induction", fr = "L’Induction du Sentier aveugle" },
    [736] = { en = "Tarnished Nightmare", fr = "Le Cauchemar terni" },
    [737] = { en = "Reflected Fury", fr = "La Fureur réfléchie" },
    [738] = { en = "The Blind", fr = "L’Aveugle" },
    [754] = { en = "Oakfather's Retribution", fr = "La Revanche du Père-Chêne" },
    [755] = { en = "Blunted Blades", fr = "Les Lames émoussées" },
    [756] = { en = "Baan Dar's Blessing", fr = "La Bénédiction de Baan Dar" },
    [757] = { en = "Symmetry of the Weald", fr = "La Symétrie du Weald" },
    [758] = { en = "Macabre Vintage", fr = "Le Cru macabre" },
    [759] = { en = "Ayleid Refuge", fr = "Le Refuge ayléide" },
    [760] = { en = "Rourken Steamguards", fr = "Les Gardes à vapeur de Rourken" },
    [761] = { en = "The Shadow Queen's Cowl", fr = "La Capuche de la Reine des ombres" },
    [762] = { en = "The Saint and the Seducer", fr = "La Sainte et la Séductrice" },
    [763] = { en = "Tharriker's Strike", fr = "La Frappe du tharriker" },
    [764] = { en = "Highland Sentinel", fr = "La Sentinelle des hautes terres" },
    [765] = { en = "Threads of War", fr = "Fils de la guerre" },
    [766] = { en = "Mora Scribe's Thesis", fr = "La Thèse de scribe de Mora" },
    [767] = { en = "Slivers of the Null Arca", fr = "Les Fragments du Null Arca" },
    [768] = { en = "Lucent Echoes", fr = "Les Échos lumineux" },
    [769] = { en = "Xoryn's Masterpiece", fr = "Le chef-d'œuvre de Xoryn" },
    [770] = { en = "Perfected Xoryn's Masterpiece", fr = "Le Chef-d'œuvre de Xoryn perfectionné" },
    [771] = { en = "Perfected Lucent Echoes", fr = "Les Échos lumineux perfectionnés" },
    [772] = { en = "Perfected Slivers of the Null Arca", fr = "Les Fragments perfectionnés du Null Arca" },
    [773] = { en = "Perfected Mora Scribe's Thesis", fr = "La Thèse de scribe de Mora perfectionnée" },
    [775] = { en = "Spattering Disjunction", fr = "La Disjonction giclante" },
    [776] = { en = "Pyrebrand", fr = "Le Brûlot" },
    [777] = { en = "Corpseburster", fr = "Brise-cadavre" },
    [778] = { en = "Umbral Edge", fr = "Le Fil ombral" },
    [779] = { en = "Beacon of Oblivion", fr = "Le Fanal d'Oblivion" },
    [780] = { en = "Aetheric Lancer", fr = "Le Lancier aéthérique" },
    [781] = { en = "Aerie's Cry", fr = "Le Cri de l'Aire" },
    [782] = { en = "Tracker's Lash", fr = "Le Fouet de traqueur" },
    [783] = { en = "Shared Pain", fr = "La Douleur partagée" },
    [784] = { en = "Siegemaster's Focus", fr = "Focalisation de maître de siège" },
    [791] = { en = "Bulwark Ruination", fr = "Désolation du rempart" },
    [792] = { en = "Farstrider", fr = "Les Arpents" },
    [793] = { en = "Netch Oil", fr = "Huile de netch" },
    [794] = { en = "Vandorallen's Resonance", fr = "La Résonance de Vandorallen" },
    [795] = { en = "Jerensi's Bladestorm", fr = "La Tempête de lames de Jerensi" },
    [796] = { en = "Lucilla's Windshield", fr = "Le Bouclier de vent de Lucilla" },
    [797] = { en = "Squall of Retribution", fr = "Le Grain punitif" },
    [798] = { en = "Heroic Unity", fr = "L’Unité héroïque" },
    [799] = { en = "Fledgling's Nest", fr = "Le Nid de jeune griffon" },
    [800] = { en = "Noxious Boulder", fr = "Le Rocher nocif" },
    [801] = { en = "Orpheon the Tactician", fr = "Orphéon le tacticien" },
    [802] = { en = "Arkay's Charity", fr = "La Charité d'Arkay" },
    [803] = { en = "Lamp Knight's Art", fr = "L’Art de chevalier de la Lampe" },
    [804] = { en = "Blackfeather Flight", fr = "Le Vol de Noireplume" },
    [805] = { en = "Three Queens Wellspring", fr = "La Source des Trois Reines" },
    [806] = { en = "Death-Dancer", fr = "Le Dansemort" },
    [807] = { en = "Full Belly Barricade", fr = "La Barricade de la Panse garnie" },
    [808] = { en = "Shared Burden", fr = "Le Fardeau partagé" },
    [809] = { en = "Tide-Born Wildstalker", fr = "Le Traquepiste Enfant-des-Marées" },
    [810] = { en = "Fellowship's Fortitude", fr = "La Camaraderie fortifiante" },
    [811] = { en = "Mad God's Dancing Shoes", fr = "Chaussures de danse du Dieu fou" },
    [812] = { en = "Rakkhat's Voidmantle", fr = "Le mantelet du vide de Rakkhat" },
    [813] = { en = "Monomyth Reforged", fr = "Le monomythe reforgé" },
    [814] = { en = "Harmony in Chaos", fr = "L’Harmonie du Chaos" },
    [815] = { en = "Kazpian's Cruel Signet", fr = "Le Sceau cruel de Kazpian" },
    [816] = { en = "Dolorous Arena", fr = "L’Arène de Douleur" },
    [817] = { en = "Recovery Convergence", fr = "La Convergence reposante" },
    [818] = { en = "Perfected Recovery Convergence", fr = "La Convergence reposante parfaite" },
    [819] = { en = "Perfected Dolorous Arena", fr = "L’Arène de Douleur parfaite" },
    [820] = { en = "Perfected Kazpian's Cruel Signet", fr = "Le Sceau cruel de Kazpian parfait" },
    [821] = { en = "Perfected Harmony in Chaos", fr = "L’Harmonie du Chaos parfaite" },
    [822] = { en = "Lustrous Soulwell", fr = "Puits des âmes riches" },
    [823] = { en = "Vykand's Soulfury", fr = "Fureur d'âmes de Vykand" },
    [824] = { en = "Black Foundry Steel", fr = "Acier de la Fonderie noire" },
    [825] = { en = "Xanmeer Spellweaver", fr = "Tissesort du xanmeer" },
    [826] = { en = "Tools of the Trapmaster", fr = "Outils du piégeur" },
    [827] = { en = "Stonehulk Domination", fr = "Domination de l'enveloppe de pierre" },
    [828] = { en = "Black Gem Monstrosity", fr = "La Monstruosité de pierre noire" },
    [829] = { en = "Bar-Sakka", fr = "Bar-Sakka" },
    [830] = { en = "Spellshredder", fr = "Lacération magique" },
    [831] = { en = "Coup De Grâce", fr = "Coup de grâce" },
    [832] = { en = "Unflinching Ultimate", fr = "Ultime impassible" },
    [845] = { en = "Huntsman's Warmask", fr = "Le Masque de guerre du Chasseur" },
    [846] = { en = "Xanmeer Genesis", fr = "Genèse du xanmeer" },
    [848] = { en = "Shattered Paths Signet", fr = "La chevalière des chemins brisés" },
    [849] = { en = "Glittering Goad", fr = "L’Aiguillon luisant" },
    [850] = { en = "Thousand Eyes", fr = "Les Mille Yeux" },
    [851] = { en = "The Ruckus", fr = "Le Vacarme" },
    [854] = { en = "Prowler's Talisman", fr = "Le talisman du Rôdeur" },
    [855] = { en = "Gorethief", fr = "Volesang" },
}
Localization.RegisterNativeNames("set", sets)
local dictionary = {}
local catalogIds = { 50, 77, 110, 122, 123, 124, 141, 147, 164, 172, 180, 181, 184, 185, 229, 232, 261, 268, 276, 318, 330, 331, 332, 333, 341, 346, 349, 388, 391, 416, 436, 446, 452, 455, 471, 476, 492, 494, 496, 516, 518, 535, 558, 562, 571, 574, 577, 585, 588, 602, 609, 622, 627, 633, 634, 641, 648, 649, 666, 672, 676, 685, 686, 687, 691, 722, 729, 731, 734, 738, 762, 768, 769, 816, 817, 849 }
for _, id in ipairs(catalogIds) do local names = sets[id]; if names then dictionary[names.en] = names.fr end end
-- Existing addon catalog headings use these shorter English names.
local aliases = { ["Martial Knowledge"] = 147, ["Morag Tong"] = 50 }
for source, id in pairs(aliases) do if sets[id] then dictionary[source] = sets[id].fr end end
Localization.Register("fr", dictionary)

-- Curated support ability names: native tooltip records and morph headings
-- exported by ESOAZ; identities cross-checked against LuiExtended/Hodor.
-- Names only: costs, timing, descriptions and live state always come from ESO.
-- https://esoaz.com/datas/live/skills/38563/cor-de-guerre/
-- https://esoaz.com/datas/live/skills/122174/colosse-gel/
-- https://esoaz.com/datas/live/skills/23495/invocation-d-atronach-charg/
-- https://esoaz.com/datas/live/skills/40237/barrire-revitalisante/
-- https://esoaz.com/datas/live/skills/32947/tendard-de-puissance/
-- https://esoaz.com/datas/live/skills/183709/glyphique-vitalisant/
-- https://esoaz.com/datas/live/skills/193794/glyphique-des-mares/
-- https://esoaz.com/datas/live/skills/25411/tnbres-dvorantes/
-- https://esoaz.com/datas/live/skills/27706/ngation-de-la-magie/
-- https://esoaz.com/datas/live/skills/21752/nova/
-- https://esoaz.com/datas/live/skills/22223/rite-de-passage/
-- https://esoaz.com/datas/live/skills/85532/bosquet-isol/
-- https://esoaz.com/datas/live/skills/86109/tempte-de-neige-fondue/
-- https://esoaz.com/datas/live/skills/83552/panace/
-- https://esoaz.com/datas/live/skills/115410/ranimation/
-- https://esoaz.com/datas/live/skills/17874/carapace-de-magma/
-- https://esoaz.com/datas/live/skills/35508/siphon-d-mes/
-- https://esoaz.com/datas/live/skills/28988/tendard-des-chevaliers-dragons/
-- https://esoaz.com/datas/live/skills/39075/chef-de-la-meute/
-- https://esoaz.com/datas/live/skills/192380/abri-ricanant-b/
local abilities = {
    [35508] = { en = "Soul Siphon", fr = "Siphon d'âmes" },
    [17874] = { en = "Magma Shell", fr = "Carapace de magma" },
    [21752] = { en = "Nova", fr = "Nova" },
    [21755] = { en = "Solar Prison", fr = "Prison solaire" },
    [21758] = { en = "Solar Disturbance", fr = "Perturbation solaire" },
    [22223] = { en = "Rite of Passage", fr = "Rite de passage" },
    [22226] = { en = "Practiced Incantation", fr = "Incantation répétée" },
    [22229] = { en = "Remembrance", fr = "Remembrance" },
    [23492] = { en = "Greater Storm Atronach", fr = "Invocation d'atronach de foudre supérieur" },
    [23495] = { en = "Summon Charged Atronach", fr = "Invocation d'atronach chargé" },
    [23634] = { en = "Summon Storm Atronach", fr = "Invocation d'atronach de foudre" },
    [25411] = { en = "Consuming Darkness", fr = "Ténèbres dévorantes" },
    [27706] = { en = "Negate Magic", fr = "Négation de la magie" },
    [28341] = { en = "Suppression Field", fr = "Champ de suppression" },
    [28348] = { en = "Absorption Field", fr = "Champ d'absorption" },
    [28988] = { en = "Dragonknight Standard", fr = "Étendard des Chevaliers-dragons" },
    [32947] = { en = "Standard of Might", fr = "Étendard de puissance" },
    [36485] = { en = "Veil of Blades", fr = "Voile de lame" },
    [36493] = { en = "Bolstering Darkness", fr = "Ténèbres rassurantes" },
    [38563] = { en = "War Horn", fr = "Cor de guerre" },
    [38573] = { en = "Barrier", fr = "Barrière" },
    [39075] = { en = "Pack Leader", fr = "Chef de la meute" },
    [40220] = { en = "Sturdy Horn", fr = "Cor de résistance" },
    [40223] = { en = "Aggressive Horn", fr = "Cor agressif" },
    [40237] = { en = "Reviving Barrier", fr = "Barrière revitalisante" },
    [40239] = { en = "Replenishing Barrier", fr = "Barrière rafraîchissante" },
    [83552] = { en = "Panacea", fr = "Panacée" },
    [83850] = { en = "Life Giver", fr = "Don de vie" },
    [85132] = { en = "Light's Champion", fr = "Champion de la lumière" },
    [85532] = { en = "Secluded Grove", fr = "Bosquet isolé" },
    [85804] = { en = "Enchanted Forest", fr = "Forêt enchantée" },
    [85807] = { en = "Healing Thicket", fr = "Fourré curatif" },
    [86109] = { en = "Sleet Storm", fr = "Tempête de neige fondue" },
    [86113] = { en = "Northern Storm", fr = "Tempête du nord" },
    [86117] = { en = "Permafrost", fr = "Permafrost" },
    [115410] = { en = "Reanimate", fr = "Réanimation" },
    [118367] = { en = "Renewing Animation", fr = "Renouvellement d'animation" },
    [118379] = { en = "Animate Blastbones", fr = "Explossements animés" },
    [122174] = { en = "Frozen Colossus", fr = "Colosse gelé" },
    [122388] = { en = "Glacial Colossus", fr = "Colosse glacial" },
    [122395] = { en = "Pestilent Colossus", fr = "Le Colosse pestilentiel" },
    [183709] = { en = "Vitalizing Glyphic", fr = "Glyphique vitalisant" },
    [192380] = { en = "Gibbering Shelter", fr = "Abri ricanant (B)" },
    [193558] = { en = "Resonating Glyphic", fr = "Glyphique résonateur" },
    [193794] = { en = "Glyphic of the Tides", fr = "Glyphique des marées" },
}
Localization.RegisterNativeNames("ability", abilities)
local abilityDictionary = {}
for _, names in pairs(abilities) do abilityDictionary[names.en] = names.fr end
Localization.Register("fr", abilityDictionary)
